cmake_minimum_required(VERSION 3.15) # РџСЂРѕРІРµСЂРєР° РІРµСЂСЃРёРё CMake.
									 # Р•СЃР»Рё РІРµСЂСЃРёСЏ СѓСЃС‚Р°РЅРѕРІР»РµРЅРѕР№ РїСЂРѕРіСЂР°РјРјС‹
									 # СЃС‚Р°СЂРµРµ СѓРєР°Р·Р°РЅРѕР№, РїСЂРѕРёР·Р°Р№РґС‘С‚ Р°РІР°СЂРёР№РЅС‹Р№ РІС‹С…РѕРґ.

set(PROJECT_NAME l1s2) 			 # Р·Р°РґР°С‚СЊ Р·РЅР°С‡РµРЅРёРµ PROJECT_NAME		 
project("${PROJECT_NAME}")           # СѓСЃС‚Р°РЅРѕРІРёС‚СЊ РёРјСЏ РїСЂРѕРµРєС‚Р°


set(CMAKE_CXX_STANDARD 20)			 # СѓСЃС‚Р°РЅР°РІР»РёРІР°РµРј 17 СЃС‚Р°РЅРґР°СЂС‚ СЏР·С‹РєР°

# РЎРєР°Р·Р°С‚СЊ РїСЂРѕРіСЂР°РјРјРµ, С‡С‚Рѕ РґРѕР»Р¶РµРЅ Р±С‹С‚СЊ РёСЃРїРѕР»РЅСЏРµРјС‹Р№ С„Р°Р№Р»
add_executable("${PROJECT_NAME}" main.cpp)
